version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    container_name: benches-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: