version: '3.8'

services:
  front-web:
    container_name: benches-web-site
    build:
      context: ./
      dockerfile: ./containers/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # <-- creates the node_modules in frontend path
      - /app/.next # <-- creates the .next folder in frontend path
