definitions:
  apperror.AppError:
    properties:
      details:
        items:
          type: integer
        type: array
      message:
        type: string
    type: object
  domain.Bench:
    properties:
      id:
        type: string
      images:
        items:
          type: string
        type: array
      is_active:
        type: boolean
      lat:
        type: number
      lng:
        type: number
    type: object
  dto.AuthorizationBot:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.CreateBenchViaTelegram:
    properties:
      images:
        items:
          items:
            type: integer
          type: array
        type: array
      lat:
        type: number
      lng:
        type: number
      user_telegram_id:
        type: integer
    type: object
  dto.CreateUser:
    properties:
      auth_date:
        type: integer
      first_name:
        type: string
      hash:
        type: string
      id:
        type: integer
      last_name:
        type: string
      photo_url:
        type: string
      username:
        type: string
    type: object
  dto.RefreshToken:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/benches/:
    get:
      description: Get list active benches
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Bench'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: List benches
      tags:
      - Benches
  /api/v1/benches/moderation:
    get:
      description: Accept or reject a bench
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperror.AppError'
      summary: Decision bench
      tags:
      - Benches Moderation
  /api/v1/benches/telegram:
    post:
      parameters:
      - description: bench data
        in: body
        name: CreateBenchViaTelegram
        required: true
        schema:
          $ref: '#/definitions/dto.CreateBenchViaTelegram'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create bench via telegram
      tags:
      - Benches Moderation
  /api/v1/bot/auth:
    post:
      parameters:
      - description: bot info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.AuthorizationBot'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "403":
          description: Forbidden
      summary: Authorization bot
      tags:
      - Bot
  /api/v1/bot/refresh:
    post:
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: token info
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Bot refresh token
      tags:
      - Bot
  /api/v1/users:
    post:
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: User registration
      tags:
      - Users
  /api/v1/users/refresh:
    post:
      parameters:
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: token info
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/dto.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: User refresh token
      tags:
      - Users
swagger: "2.0"
