name: Benches Site Build & Deploy

on:
  push:
    branches:
      - frontend/development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Create env file'
        run: |
          touch .env.local
          echo BOT_USERNAME=${{ secrets.BOT_USERNAME }} >> .env
          echo BASE_URL=${{ secrets.BASE_URL }} >> .env
          echo YANDEX_KEY=${{ secrets.YANDEX_KEY }} >> .env
          echo BOT_ID=${{ secrets.BOT_ID }} >> .env
          cat .env

      - name: Build container
        run: docker-compose up -d --build

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Deploy
#        uses: appleboy/ssh-action@master
#
#        with:
#          HOST: ${{ secrets.FRONTEND_DEPLOY_HOST }}
#          USERNAME: ${{ secrets.FRONTEND_DEPLOY_USER }}
#          PORT: ${{ secrets.FRONTEND_DEPLOY_PORT }}
#          KEY: ${{ secrets.FRONTEND_DEPLOY_SSH_KEY }}
#          script: cd ${{ secrets.FRONTEND_PWD }} && git pull && docker-compose down && docker-compose up -d
